*: use a simpler print format and display all output to user
This utilizes our new way of handling output from steps. Any printf with a
'result:' prefix will be recorded for the summary screen, everything else will
be printed to the user in the statusbar for continuous updates on what the spell
is doing in the bg.

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

diff --git a/kubernetes-core/steps/00_pre-deploy b/kubernetes-core/steps/00_pre-deploy
--- a/kubernetes-core/steps/00_pre-deploy
+++ b/kubernetes-core/steps/00_pre-deploy
@@ -5,9 +5,10 @@ set -eu
 . $CONJURE_UP_SPELLSDIR/sdk/common.sh
 
 if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
-    debug "Running pre-deploy for $CONJURE_UP_SPELL"
-    lxc storage create conjureup dir >/dev/null 2>&1 || debug "Storage pool conjureup already exists" && true
-    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || exposeResult "Failed to set profile" $? "false"
+    printf "Running pre-deploy for LXD container\n"
+    lxc storage create conjureup dir || true
+    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || printf "result: Failed to set profile" && exit 1
 fi
 
-exposeResult "Successful pre-deploy." 0 "true"
+printf "result: Successful pre-deploy"
+exit 0
