openstack-novalxd: use redis backend
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

diff --git a/openstack-novalxd/steps/00_pre-deploy b/openstack-novalxd/steps/00_pre-deploy
--- a/openstack-novalxd/steps/00_pre-deploy
+++ b/openstack-novalxd/steps/00_pre-deploy
@@ -2,13 +2,13 @@
 
 set -eu
 
-. $CONJURE_UP_SPELLSDIR/sdk/common.sh
+. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"
 
 if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
     debug "Running pre-deploy for $CONJURE_UP_SPELL"
     lxc storage create conjureup dir >/dev/null 2>&1 || debug "Storage pool conjureup already exists" && true
-    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || printf "Failed to set profile" && exit 0
+    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || setResult "Failed to set profile" && exit 1
 fi
 
-printf "result: Successful pre-deploy."
+setResult "Successful pre-deploy."
 exit 0
