*: macOS compat
No recent readlink on macOS, rework all spells to utilize the sdk for
determining SCRIPTPATH

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

diff --git a/canonical-kubernetes/steps/00_pre-deploy b/canonical-kubernetes/steps/00_pre-deploy
--- a/canonical-kubernetes/steps/00_pre-deploy
+++ b/canonical-kubernetes/steps/00_pre-deploy
@@ -2,17 +2,11 @@
 
 set -eu
 
-# Path to executing script
-SCRIPT=$(readlink -e $0)
-
-# Directory housing script
-SCRIPTPATH=$(dirname $SCRIPT)
-
 . $CONJURE_UP_SPELLSDIR/sdk/common.sh
 
 if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
     debug "Running pre-deploy for $CONJURE_UP_SPELL"
-    sed "s/##MODEL##/$JUJU_MODEL/" $SCRIPTPATH/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || exposeResult "Failed to set profile" $? "false"
+    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || exposeResult "Failed to set profile" $? "false"
 fi
 
 exposeResult "Successful pre-deploy." 0 "true"
